name: navid
favicon: null
layout_spectrum: 0.35146
typography_spectrum: 0.43004
title: Navid Nakhjiri PhD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a06'
    - '#fdfcf7'
    - '#404040'
    - '#857c75'
    - '#d8372f'
  brandStrength: 0.9485320337116718
  lightness: 0.3130024776328355
  saturation: 0.49933720799162984
  rhythmicContrast: 0.3190275945235044
purpose: []
