name: navid
favicon: null
layout_spectrum: 0.99226
typography_spectrum: 0.43663
title: Navid Nakhjiri PhD
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a06'
    - '#fdfcf7'
    - '#404040'
    - '#857c75'
    - '#d8372f'
  brandStrength: 0.125
  lightness: 0.3130024776328355
  saturation: 0.4993372079916298
  rhythmicContrast: 0.3190275945235044
purpose: []
